bug fixes

diff --git a/.github/workflows/go-app.yaml b/.github/workflows/go-app.yaml
--- a/.github/workflows/go-app.yaml
+++ b/.github/workflows/go-app.yaml
@@ -16,7 +16,7 @@ jobs:
           go-version: ${{ vars.GO_VERSION}}
 
       - name: Test this code before building
-        run: go test ../.. . && echo "Test case if success"; exit 0 || ( echo "Test cases failed..."; exit 1)
+        run: go test ./...  && echo "Test case if success"; exit 0 || ( echo "Test cases failed..."; exit 1)
       -
         name: Login to Docker Registry
         uses: docker/login-action@v4
